from pak.function import *

def choose(func):
    if func=='Fn1S':
        return [Fn1S,F1]
    elif func=='Fn2S':
        return [Fn2S,F2]
    elif func=='Fn7S':
        return [Fn7S,F7]
    elif func=='Fn8S':
        return [Fn8S,F8]
    elif func=='Fn10S':
        return [Fn10S,F10]
    elif func=='Fn13S':
        return [Fn13S,F13]
    elif func=='Fn18S':
        return [Fn18S,F18]
    elif func=='Fn19S':
        return [Fn19S,F19]
    elif func=='Fn22S':
        return [Fn22S,F22]
    if func=='Fn1M':
        return [Fn1M,F1]
    elif func=='Fn2M':
        return [Fn2M,F2]
    elif func=='Fn7M':
        return [Fn7M,F7]
    elif func=='Fn8M':
        return [Fn8M,F8]
    elif func=='Fn10M':
        return [Fn10M,F10]
    elif func=='Fn13M':
        return [Fn13M,F13]
    elif func=='Fn18M':
        return [Fn18M,F18]
    elif func=='Fn19M':
        return [Fn19M,F19]
    elif func=='Fn22M':
        return [Fn22M,F22]
    if func=='Fn1L':
        return [Fn1L,F1]
    elif func=='Fn2L':
        return [Fn2L,F2]
    elif func=='Fn7L':
        return [Fn7L,F7]
    elif func=='Fn8L':
        return [Fn8L,F8]
    elif func=='Fn10L':
        return [Fn10L,F10]
    elif func=='Fn13L':
        return [Fn13L,F13]
    elif func=='Fn18L':
        return [Fn18L,F18]
    elif func=='Fn19L':
        return [Fn19L,F19]
    elif func=='Fn22L':
        return [Fn22L,F22]
    else:
        print('No such function')